name: smoke
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - codex/v12.3.0
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
  pull_request:
    branches: main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.txt'
jobs:
  style:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.10"
          architecture: x64

      - name: Packages
        run: python -m pip install -r tests/requirements.txt

      - name: Linters
        run: |
          python -m black --check av examples tests setup.py
          python -m flake8 av examples tests
          python -m isort --check-only --diff av examples tests
          python -m mypy av tests
        shell: bash

  windows:
    name: "py-3.8.10 lib-${{ matrix.ffmpeg }} windows"
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        ffmpeg: ["6.1", "6.0"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Conda
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda config --set always_yes true
        conda config --add channels conda-forge
        conda create -q -n pyav \
          cython \
          numpy \
          pillow \
          python=3.8.10 \
          setuptools

    - name: Build
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda activate pyav
        python -c "import sys; assert sys.version_info[:3] == (3, 8, 10), sys.version"
        python scripts\\fetch-vendor.py --config-file scripts\\ffmpeg-${{ matrix.ffmpeg }}.json $CONDA_PREFIX\\Library
        python setup.py build_ext --inplace --ffmpeg-dir=$CONDA_PREFIX\\Library

    - name: Test
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda activate pyav
        python -c "import sys; assert sys.version_info[:3] == (3, 8, 10), sys.version"
        python -m unittest discover -t . -s tests
